### ISSUE TITLE
Immersion Addon not working;

### ISSUE THREAD

**Issue by Ub3rZ4cH** [z0fa/WoWQuestTTS#1] opened 2022-01-25 01:04 UTC
Hi, firstly thanks this addon is awesome, however I noticed it is meant to work with the addon immersion? however when I have immersion installed the play button does nothing. (could this be because immersion is out date right now and I have to enable out of date addons)

**Comment by z0fa** [comment] 2022-01-25 17:16
Thank you for opening the issue. It seems to be a problem caused by some changes made by Blizzard to the GetTexture function. I have just pushed a fix, can you please update the addon and verify if the problem is resolved?

**Comment by Ub3rZ4cH** [comment] 2022-01-25 17:39
Hey thanks, it works now, thank you :).

On another note I have been trying to change the voice, but that I think its related to WoW accessibility feature not detecting the new voices I installed in Windows, as I understand your addon uses those voices? Is there a way to change the voice in any other way. 

Ps. this combined with immersion makes quests way more fun, and I really appreciate your work on this addon.

**Comment by Ub3rZ4cH** [comment] 2022-01-25 22:00
Hey, so it works but on a quest hand in, it only reads the title. 
![Screenshot (20)](https://user-images.githubusercontent.com/2918031/151066880-e68a28f1-aab7-43ff-8659-965f16b91af8.png)

**Comment by z0fa** [comment] 2022-01-26 17:15
> Hey thanks, it works now, thank you :).
> 
> On another note I have been trying to change the voice, but that I think its related to WoW accessibility feature not detecting the new voices I installed in Windows, as I understand your addon uses those voices? Is there a way to change the voice in any other way.
> 
> Ps. this combined with immersion makes quests way more fun, and I really appreciate your work on this addon.

Nope, if the voices don't show up in the accessibility window the can't be used by addons...



> Hey, so it works but on a quest hand in, it only reads the title. ![Screenshot (20)](https://user-images.githubusercontent.com/2918031/151066880-e68a28f1-aab7-43ff-8659-965f16b91af8.png)

The problem happens with this specific quest only?

**Comment by Ub3rZ4cH** [comment] 2022-01-27 02:28
> The problem happens with this specific quest only?

No, sorry it happens with every NPC that has a hand in "?". The dialog they say before you hand in the quest is what doesnt read now, it just reads the title. However when the npc has "!" it works.

**Comment by z0fa** [comment] 2022-01-27 20:21
Okay now should be working. You need to comment out the parts that you want to sto from being read in the ReadQuest function, there is a source variable that indicates where the addon is reading the text. For example if you want to only read the quest description in the quest log (the panel that shows up when you open the map) you need to edit this:

```lua
if (source == "questlog") then
    local title = C_QuestLog.GetTitleForQuestID(QuestMapFrame_GetFocusedQuestID())
    local description, objective = GetQuestLogQuestText()
    text = title .. "\n" .. description .. "\n" .. objective
```

to this:

```lua
if (source == "questlog") then
    local title = C_QuestLog.GetTitleForQuestID(QuestMapFrame_GetFocusedQuestID())
    local description, objective = GetQuestLogQuestText()
    text = description
```

Maybe I'll add some options to control this behaviours soon or later...

**Comment by Ub3rZ4cH** [comment] 2022-01-28 19:07
https://user-images.githubusercontent.com/2918031/151605319-80d15b24-94f5-485a-bd3d-24d506c107c8.mp4

Hey sorry but it doesnt work still for the quest hand in dialog. 
Without Immersion it reads the quest hand in dialog fine. 
And thanks for the help with the edits, I am now able to get it to only read the description.

**Comment by z0fa** [comment] 2022-01-28 20:54
Ookay I have pushed another fix, all the cases should now have been handled correctly, maybe... 🤣

**Closed** 2022-06-04 17:00 UTC
